<script setup lang="ts">
import { request } from '~/api/client'

const pending = ref(false)
const error = ref('')
const message = ref('')
const form = reactive({
  artistName: '', organizationName: 'Independent musician', countryCode: '', taxResidenceCountry: '',
  registrationData: { title: '', legalLastName: '', legalFirstName: '', otherNames: '', idType: '', idNumber: '', nationality: '', dateOfBirth: '', roles: [] as string[], gender: '', email: '', phone: '', region: '', district: '', residentialAddress: '', digitalAddress: '', hometown: '', socialLinks: { instagram: '', facebook: '', x: '', youtube: '', website: '' }, recordLabel: '', performingRightsMember: 'no' as 'yes' | 'no', mechanicalRightsMember: 'no' as 'yes' | 'no', excludeTerritories: 'no' as 'yes' | 'no', excludedCountries: '', paymentDetails: 'bank' as 'bank' | 'mobile_money' | 'both', nextOfKin: { name: '', relationship: '', phone: '' }, termsAccepted: false }
})
const roleOptions = ['Composer', 'Lyricist', 'Performer', 'Producer', 'Publisher', 'Author']

onMounted(async () => {
  try { const { profile } = await request<{ profile: typeof form | null }>('/onboarding'); if (profile) Object.assign(form, profile) } catch (caught) { error.value = caught instanceof Error ? caught.message : 'Unable to load profile.' }
})

async function save() {
  error.value = ''; message.value = ''
  if (!form.registrationData.termsAccepted) { error.value = 'Accept the terms and conditions before submitting.'; return }
  if (!form.registrationData.legalFirstName || !form.registrationData.legalLastName || !form.registrationData.phone || !form.registrationData.idNumber) { error.value = 'Complete your legal name, ID number, and phone number.'; return }
  pending.value = true
  try { await request('/onboarding', { method: 'POST', body: JSON.stringify({ ...form, status: 'in_process' }) }); message.value = 'Registration saved and submitted for OKSBI review.' } catch (caught) { error.value = caught instanceof Error ? caught.message : 'Unable to save registration.' } finally { pending.value = false }
}
</script>

<template>
  <section class="workspace-copy registration-page">
    <header class="registration-hero"><div><span class="eyebrow">Musician registration</span><h1 class="page-title">Build your artist profile.</h1><p class="helper-text">Complete your identity, contact, rights, and payment details. OKSBI will review your application before music can be submitted.</p></div><span class="registration-step">01 <small>/ 02</small></span></header>
    <form class="registration-form" @submit.prevent="save">
      <section class="surface registration-section"><div class="registration-section-heading"><span>01</span><div><h2>Personal identity</h2><p>Use the details that appear on your official identity documents.</p></div></div><div class="registration-grid"><label class="form-label">Title<select v-model="form.registrationData.title" class="form-field"><option value="">Select</option><option>Mr</option><option>Ms</option><option>Mrs</option><option>Dr</option></select></label><label class="form-label">First name<input v-model="form.registrationData.legalFirstName" class="form-field" required /></label><label class="form-label">Last name<input v-model="form.registrationData.legalLastName" class="form-field" required /></label><label class="form-label">Other name(s)<input v-model="form.registrationData.otherNames" class="form-field" /></label><label class="form-label">Stage name / pseudonym<input v-model="form.artistName" class="form-field" required /></label><label class="form-label">Date of birth<input v-model="form.registrationData.dateOfBirth" class="form-field" type="date" /></label><label class="form-label">ID type<select v-model="form.registrationData.idType" class="form-field" required><option value="">Select</option><option>National ID</option><option>Passport</option><option>Driving licence</option></select></label><label class="form-label">ID number<input v-model="form.registrationData.idNumber" class="form-field" required /></label><label class="form-label">Nationality<input v-model="form.registrationData.nationality" class="form-field" required /></label><label class="form-label">Gender<select v-model="form.registrationData.gender" class="form-field"><option value="">Select</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Prefer not to say</option></select></label></div><fieldset class="registration-fieldset"><legend>Role(s)</legend><label v-for="role in roleOptions" :key="role" class="check-option"><input v-model="form.registrationData.roles" type="checkbox" :value="role" /> {{ role }}</label></fieldset></section>
      <section class="surface registration-section"><div class="registration-section-heading"><span>02</span><div><h2>Contact and location</h2><p>Where OKSBI can reach you and where your work is based.</p></div></div><div class="registration-grid"><label class="form-label">Email<input v-model="form.registrationData.email" class="form-field" type="email" /></label><label class="form-label">Phone number<input v-model="form.registrationData.phone" class="form-field" type="tel" required /></label><label class="form-label">Country code<input v-model="form.countryCode" class="form-field" maxlength="2" placeholder="GH" required /></label><label class="form-label">Tax residence country<input v-model="form.taxResidenceCountry" class="form-field" maxlength="2" placeholder="GH" required /></label><label class="form-label">Region<input v-model="form.registrationData.region" class="form-field" /></label><label class="form-label">District<input v-model="form.registrationData.district" class="form-field" /></label><label class="form-label registration-wide">Residential address<textarea v-model="form.registrationData.residentialAddress" class="textarea-field" rows="2" /></label><label class="form-label">Digital address<input v-model="form.registrationData.digitalAddress" class="form-field" /></label><label class="form-label">Hometown<input v-model="form.registrationData.hometown" class="form-field" /></label><label class="form-label">Record label (optional)<input v-model="form.registrationData.recordLabel" class="form-field" /></label><label class="form-label">Organization<input v-model="form.organizationName" class="form-field" required /></label></div></section>
      <section class="surface registration-section"><div class="registration-section-heading"><span>03</span><div><h2>Online presence</h2><p>Optional links help us identify and support your artist profile.</p></div></div><div class="registration-grid"><label class="form-label">Instagram<input v-model="form.registrationData.socialLinks.instagram" class="form-field" placeholder="https://instagram.com/" /></label><label class="form-label">Facebook<input v-model="form.registrationData.socialLinks.facebook" class="form-field" /></label><label class="form-label">X / Twitter<input v-model="form.registrationData.socialLinks.x" class="form-field" /></label><label class="form-label">YouTube<input v-model="form.registrationData.socialLinks.youtube" class="form-field" /></label><label class="form-label registration-wide">Website<input v-model="form.registrationData.socialLinks.website" class="form-field" type="url" /></label></div></section>
      <section class="surface registration-section"><div class="registration-section-heading"><span>04</span><div><h2>Rights and payment</h2><p>Tell us about existing memberships and how you prefer to receive payments.</p></div></div><div class="registration-grid"><label class="form-label">Performing rights society membership<select v-model="form.registrationData.performingRightsMember" class="form-field"><option value="no">No</option><option value="yes">Yes</option></select></label><label class="form-label">Mechanical rights society membership<select v-model="form.registrationData.mechanicalRightsMember" class="form-field"><option value="no">No</option><option value="yes">Yes</option></select></label><label class="form-label">Exclude countries from rights territory?<select v-model="form.registrationData.excludeTerritories" class="form-field"><option value="no">No</option><option value="yes">Yes</option></select></label><label v-if="form.registrationData.excludeTerritories === 'yes'" class="form-label">Countries to exclude<input v-model="form.registrationData.excludedCountries" class="form-field" placeholder="Separate countries with commas" /></label><label class="form-label">Payment details to provide<select v-model="form.registrationData.paymentDetails" class="form-field"><option value="bank">Bank only</option><option value="mobile_money">Mobile money only</option><option value="both">Bank and mobile money</option></select></label></div></section>
      <section class="surface registration-section"><div class="registration-section-heading"><span>05</span><div><h2>Next of kin and consent</h2><p>A successor contact for your account and your confirmation to submit.</p></div></div><div class="registration-grid"><label class="form-label">Next of kin name<input v-model="form.registrationData.nextOfKin.name" class="form-field" /></label><label class="form-label">Relationship<input v-model="form.registrationData.nextOfKin.relationship" class="form-field" /></label><label class="form-label">Phone number<input v-model="form.registrationData.nextOfKin.phone" class="form-field" /></label></div><label class="check-option terms-option"><input v-model="form.registrationData.termsAccepted" type="checkbox" /> I agree to the OKSBI terms and confirm that the information provided is accurate.</label></section>
      <p v-if="error" class="validation-note" role="alert">{{ error }}</p><p v-if="message" class="helper-text" role="status">{{ message }}</p><div class="registration-actions"><button class="primary-button" :disabled="pending">{{ pending ? 'Saving registration...' : 'Submit registration for review' }}</button><NuxtLink class="secondary-button" to="/catalog">Continue to My music</NuxtLink></div>
    </form>
  </section>
</template>

<style scoped>
.registration-page { gap: 18px; }.registration-hero { display: flex; align-items: end; justify-content: space-between; gap: 30px; padding: 30px; border-radius: 28px; background: linear-gradient(135deg, #18232b, #34504a); color: #fffaf2; }.registration-hero .page-title { max-width: 650px; margin: 8px 0; color: #fffaf2; }.registration-hero .helper-text { max-width: 650px; color: rgba(255,250,242,.72); }.registration-step { color: #f2b09d; font-family: Fraunces, Georgia, serif; font-size: 3rem; white-space: nowrap; }.registration-step small { color: rgba(255,250,242,.6); font-family: Manrope, sans-serif; font-size: .9rem; }.registration-form { display: flex; flex-direction: column; gap: 18px; }.registration-section { display: flex; flex-direction: column; gap: 24px; }.registration-section-heading { display: flex; gap: 18px; align-items: start; border-bottom: 1px solid var(--line); padding-bottom: 18px; }.registration-section-heading > span { color: var(--coral); font-family: Fraunces, Georgia, serif; font-size: 1.8rem; }.registration-section-heading h2 { margin: 0 0 5px; font-family: Fraunces, Georgia, serif; font-size: 1.8rem; font-weight: 600; }.registration-section-heading p { margin: 0; color: #6b7775; font-size: .8rem; }.registration-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 16px; }.registration-wide { grid-column: 1 / -1; }.registration-fieldset { display: flex; flex-wrap: wrap; gap: 12px 22px; border: 0; margin: 0; padding: 0; }.registration-fieldset legend { width: 100%; margin-bottom: 4px; color: #6b7775; font-size: .78rem; font-weight: 800; }.check-option { color: #43504f; font-size: .82rem; }.check-option input { accent-color: var(--coral); margin-right: 6px; }.terms-option { border-top: 1px solid var(--line); padding-top: 18px; }.registration-actions { display: flex; flex-wrap: wrap; gap: 10px; }
@media (max-width: 700px) { .registration-hero { align-items: start; flex-direction: column; }.registration-grid { grid-template-columns: 1fr; }.registration-wide { grid-column: auto; } }
</style>
